/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_listings__listing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_watchlists_get"];
        put?: never;
        /** Create */
        post: operations["create_api_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_watchlists__watchlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{watchlist_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_api_watchlists__watchlist_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComparableRead */
        ComparableRead: {
            /** Evidence Type */
            evidence_type: string;
            /** Final Weight Bp */
            final_weight_bp: number;
            /** Market Evidence Id */
            market_evidence_id: string;
            /** Price Minor */
            price_minor: number;
            /** Provider */
            provider: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Title */
            title: string;
        };
        /** CostRead */
        CostRead: {
            /** High Minor */
            high_minor: number;
            /** Kind */
            kind: string;
            /** Low Minor */
            low_minor: number;
            /** Rationale */
            rationale: string;
        };
        /** FeedItemRead */
        FeedItemRead: {
            /** Asking Price Minor */
            asking_price_minor: number;
            /** Confidence Bp */
            confidence_bp: number;
            /** Conservative Advantage Minor */
            conservative_advantage_minor: number | null;
            /** Fair Value Low Minor */
            fair_value_low_minor: number | null;
            /** Image Url */
            image_url: string | null;
            /** Listing Id */
            listing_id: string;
            /** Opportunity Label */
            opportunity_label: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListingDetailRead */
        ListingDetailRead: {
            /** Attributes */
            attributes: {
                [key: string]: string | number | null;
            };
            /** Comparables */
            comparables: components["schemas"]["ComparableRead"][];
            /** Confidence Bp */
            confidence_bp: number;
            /** Conservative Advantage Minor */
            conservative_advantage_minor: number | null;
            /** Costs */
            costs: components["schemas"]["CostRead"][];
            /** Fair Value High Minor */
            fair_value_high_minor: number | null;
            /** Fair Value Low Minor */
            fair_value_low_minor: number | null;
            /** Fair Value Midpoint Minor */
            fair_value_midpoint_minor: number | null;
            /** Image Urls */
            image_urls: string[];
            /** Listing Id */
            listing_id: string;
            /** Observations */
            observations: components["schemas"]["ObservationRead"][];
            /** Opportunity Label */
            opportunity_label: string;
            /** Provider Status */
            provider_status: string;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
            /** Total Cost High Minor */
            total_cost_high_minor: number | null;
            /** Total Cost Low Minor */
            total_cost_low_minor: number | null;
        };
        /** LiveResponse */
        LiveResponse: {
            /**
             * Service
             * @default resale-monitor
             * @constant
             */
            service: "resale-monitor";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ObservationRead */
        ObservationRead: {
            /** Asking Price Minor */
            asking_price_minor: number | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Provider Status */
            provider_status: string;
            /** Retrieval Outcome */
            retrieval_outcome: string;
        };
        /** ReadinessChecks */
        ReadinessChecks: {
            /**
             * Database
             * @default ok
             * @constant
             */
            database: "ok";
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            checks: components["schemas"]["ReadinessChecks"];
            /**
             * Service
             * @default resale-monitor
             * @constant
             */
            service: "resale-monitor";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ReferenceRead */
        ReferenceRead: {
            /** Evidence Type */
            evidence_type: string;
            /** Listing Id */
            listing_id: string;
            /** Location Text */
            location_text: string | null;
            /** Price Minor */
            price_minor: number;
            /** Title */
            title: string;
        };
        /** SearchScopeRead */
        SearchScopeRead: {
            /** Enabled */
            enabled: boolean;
            /** Geography */
            geography: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Purpose */
            purpose: string;
            /** Query */
            query: {
                [key: string]: unknown;
            };
        };
        /** SourceHealthRead */
        SourceHealthRead: {
            /** Changed Listings */
            changed_listings: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Finished At */
            finished_at: string | null;
            /** New Listings */
            new_listings: number;
            /** Purpose */
            purpose: string;
            /** Records Seen */
            records_seen: number;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistCreate */
        WatchlistCreate: {
            /** Center Place */
            center_place: string;
            /** Maximum Price Minor */
            maximum_price_minor?: number | null;
            /** Minimum Price Minor */
            minimum_price_minor?: number | null;
            /** Name */
            name: string;
            /** Query */
            query: string;
            /** Radius Miles */
            radius_miles: number;
        };
        /** WatchlistDetailRead */
        WatchlistDetailRead: {
            /** Feed */
            feed: components["schemas"]["FeedItemRead"][];
            /** Reference Count */
            reference_count: number;
            /** References */
            references: components["schemas"]["ReferenceRead"][];
            /** Source Health */
            source_health: components["schemas"]["SourceHealthRead"][];
        };
        /** WatchlistRead */
        WatchlistRead: {
            /** Category */
            category: string;
            /** Center Place */
            center_place: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string;
            /** Id */
            id: string;
            /** Maximum Price Minor */
            maximum_price_minor: number | null;
            /** Minimum Price Minor */
            minimum_price_minor: number | null;
            /** Name */
            name: string;
            /** Radius Miles */
            radius_miles: number;
            /** Scopes */
            scopes: components["schemas"]["SearchScopeRead"][];
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readiness_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    liveness_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    detail_api_listings__listing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"][];
                };
            };
        };
    };
    create_api_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_watchlists__watchlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_watchlists__watchlist_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
