"""add watchlist marketplace domain

Revision ID: 6a3fd871238f
Revises: 20260821_0001
Create Date: 2026-08-21 15:13:20.735315
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6a3fd871238f"
down_revision: str | None = "20260821_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("local_relative_path", sa.Text(), nullable=True),
        sa.Column("display_strategy", sa.String(length=20), nullable=False),
        sa.Column("retention_status", sa.String(length=30), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=True),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("current_status", sa.String(length=30), nullable=False),
        sa.Column("status_confidence_bp", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "watchlists",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("center_place", sa.String(length=200), nullable=False),
        sa.Column("radius_meters", sa.Integer(), nullable=False),
        sa.Column("minimum_price_minor", sa.Integer(), nullable=True),
        sa.Column("maximum_price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("preferences_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_successful_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "listing_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("listing_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_listing_id", sa.String(length=200), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_missing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_provider_status", sa.String(length=30), nullable=False),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_listing_id"),
    )
    op.create_table(
        "search_scopes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("watchlist_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("query_json", sa.JSON(), nullable=False),
        sa.Column("geography_json", sa.JSON(), nullable=False),
        sa.Column("provider_filters_json", sa.JSON(), nullable=False),
        sa.Column("cadence_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("authorization_mode", sa.String(length=30), nullable=False),
        sa.Column("adapter_version", sa.String(length=30), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_succeeded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "provider", "purpose"),
    )
    op.create_index(
        "ix_search_scopes_due",
        "search_scopes",
        ["enabled", "next_run_at"],
        unique=False,
    )
    op.create_table(
        "watchlist_listings",
        sa.Column("watchlist_id", sa.String(length=36), nullable=False),
        sa.Column("listing_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("first_discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feed_state", sa.String(length=20), nullable=False),
        sa.Column("latest_analysis_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
        ),
        sa.PrimaryKeyConstraint("watchlist_id", "listing_id", "role"),
    )
    op.create_index(
        "ix_watchlist_feed",
        "watchlist_listings",
        ["watchlist_id", "role", "feed_state", "last_changed_at"],
        unique=False,
    )
    op.create_table(
        "outcome_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("listing_source_id", sa.String(length=36), nullable=False),
        sa.Column("outcome_type", sa.String(length=30), nullable=False),
        sa.Column("final_price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provenance_json", sa.JSON(), nullable=False),
        sa.Column("confidence_bp", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_source_id"],
            ["listing_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("search_scope_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("adapter_version", sa.String(length=30), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_seen", sa.Integer(), nullable=False),
        sa.Column("new_listings", sa.Integer(), nullable=False),
        sa.Column("changed_listings", sa.Integer(), nullable=False),
        sa.Column("rejected_records", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["search_scope_id"],
            ["search_scopes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_source_runs_lease",
        "source_runs",
        ["status", "lease_expires_at"],
        unique=False,
    )
    op.create_table(
        "source_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_run_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_record_id", sa.String(length=200), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_run_id"],
            ["source_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_run_id", "content_hash"),
    )
    op.create_table(
        "listing_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("listing_id", sa.String(length=36), nullable=False),
        sa.Column("listing_source_id", sa.String(length=36), nullable=False),
        sa.Column("source_record_id", sa.String(length=36), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieval_outcome", sa.String(length=30), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location_text", sa.String(length=200), nullable=True),
        sa.Column("asking_price_minor", sa.Integer(), nullable=True),
        sa.Column("shipping_price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("provider_status", sa.String(length=30), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_source_id"],
            ["listing_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listing_observations_content_hash"),
        "listing_observations",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        "ix_listing_observations_timeline",
        "listing_observations",
        ["listing_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "item_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("listing_id", sa.String(length=36), nullable=False),
        sa.Column("based_on_observation_id", sa.String(length=36), nullable=False),
        sa.Column("previous_version_id", sa.String(length=36), nullable=True),
        sa.Column("version_kind", sa.String(length=30), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("model_year", sa.Integer(), nullable=True),
        sa.Column("displacement_cc", sa.Integer(), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("running_state", sa.String(length=30), nullable=True),
        sa.Column("title_state", sa.String(length=30), nullable=True),
        sa.Column("normalized_condition", sa.String(length=30), nullable=True),
        sa.Column("category_attributes_json", sa.JSON(), nullable=False),
        sa.Column("overall_confidence_bp", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["based_on_observation_id"],
            ["listing_observations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["item_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_item_versions_displacement_cc"),
        "item_versions",
        ["displacement_cc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_versions_make"), "item_versions", ["make"], unique=False
    )
    op.create_index(
        op.f("ix_item_versions_model"), "item_versions", ["model"], unique=False
    )
    op.create_index(
        op.f("ix_item_versions_model_year"),
        "item_versions",
        ["model_year"],
        unique=False,
    )
    op.create_table(
        "observation_images",
        sa.Column("observation_id", sa.String(length=36), nullable=False),
        sa.Column("image_asset_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_asset_id"],
            ["image_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["listing_observations.id"],
        ),
        sa.PrimaryKeyConstraint("observation_id", "image_asset_id"),
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("listing_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_observation_id", sa.String(length=36), nullable=False),
        sa.Column("item_version_id", sa.String(length=36), nullable=True),
        sa.Column("valuation_policy_version", sa.String(length=30), nullable=False),
        sa.Column("analysis_status", sa.String(length=30), nullable=False),
        sa.Column("fair_value_low_minor", sa.Integer(), nullable=True),
        sa.Column("fair_value_midpoint_minor", sa.Integer(), nullable=True),
        sa.Column("fair_value_high_minor", sa.Integer(), nullable=True),
        sa.Column("total_cost_low_minor", sa.Integer(), nullable=True),
        sa.Column("total_cost_high_minor", sa.Integer(), nullable=True),
        sa.Column("conservative_advantage_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("confidence_bp", sa.Integer(), nullable=False),
        sa.Column("opportunity_label", sa.String(length=30), nullable=False),
        sa.Column("evidence_summary_json", sa.JSON(), nullable=False),
        sa.Column("risk_summary_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_observation_id"],
            ["listing_observations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_version_id"],
            ["item_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_analyses_history", "analyses", ["listing_id", "created_at"], unique=False
    )
    op.create_table(
        "attribute_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_version_id", sa.String(length=36), nullable=False),
        sa.Column("field_path", sa.String(length=200), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("evidence_kind", sa.String(length=30), nullable=False),
        sa.Column("observation_id", sa.String(length=36), nullable=True),
        sa.Column("confidence_bp", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_version_id"],
            ["item_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["listing_observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "market_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.String(length=30), nullable=False),
        sa.Column("listing_observation_id", sa.String(length=36), nullable=True),
        sa.Column("outcome_evidence_id", sa.String(length=36), nullable=True),
        sa.Column("item_version_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("shipping_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("location_text", sa.String(length=200), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provenance_json", sa.JSON(), nullable=False),
        sa.Column("natural_fingerprint", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_version_id"],
            ["item_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_observation_id"],
            ["listing_observations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["outcome_evidence_id"],
            ["outcome_evidence.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("natural_fingerprint"),
    )
    op.create_index(
        "ix_market_evidence_lookup",
        "market_evidence",
        ["evidence_type", "observed_at", "currency"],
        unique=False,
    )
    op.create_table(
        "analysis_comparables",
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("market_evidence_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("similarity_bp", sa.Integer(), nullable=False),
        sa.Column("reliability_bp", sa.Integer(), nullable=False),
        sa.Column("recency_bp", sa.Integer(), nullable=False),
        sa.Column("geography_bp", sa.Integer(), nullable=False),
        sa.Column("final_weight_bp", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("reason_codes_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_evidence_id"],
            ["market_evidence.id"],
        ),
        sa.PrimaryKeyConstraint("analysis_id", "market_evidence_id"),
    )
    op.create_table(
        "analysis_costs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("cost_kind", sa.String(length=30), nullable=False),
        sa.Column("low_minor", sa.Integer(), nullable=False),
        sa.Column("high_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("basis", sa.String(length=20), nullable=False),
        sa.Column("confidence_bp", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis_costs")
    op.drop_table("analysis_comparables")
    op.drop_index("ix_market_evidence_lookup", table_name="market_evidence")
    op.drop_table("market_evidence")
    op.drop_table("attribute_evidence")
    op.drop_index("ix_analyses_history", table_name="analyses")
    op.drop_table("analyses")
    op.drop_table("observation_images")
    op.drop_index(op.f("ix_item_versions_model_year"), table_name="item_versions")
    op.drop_index(op.f("ix_item_versions_model"), table_name="item_versions")
    op.drop_index(op.f("ix_item_versions_make"), table_name="item_versions")
    op.drop_index(op.f("ix_item_versions_displacement_cc"), table_name="item_versions")
    op.drop_table("item_versions")
    op.drop_index("ix_listing_observations_timeline", table_name="listing_observations")
    op.drop_index(
        op.f("ix_listing_observations_content_hash"), table_name="listing_observations"
    )
    op.drop_table("listing_observations")
    op.drop_table("source_records")
    op.drop_index("ix_source_runs_lease", table_name="source_runs")
    op.drop_table("source_runs")
    op.drop_table("outcome_evidence")
    op.drop_index("ix_watchlist_feed", table_name="watchlist_listings")
    op.drop_table("watchlist_listings")
    op.drop_index("ix_search_scopes_due", table_name="search_scopes")
    op.drop_table("search_scopes")
    op.drop_table("listing_sources")
    op.drop_table("watchlists")
    op.drop_table("listings")
    op.drop_table("image_assets")
    # ### end Alembic commands ###
